[build]
  base    = "erp2"
  command = "npm run build"
  publish = "erp2/dist"

[dev]
  framework  = "#custom"
  command    = "npm run dev:vite"
  targetPort = 5173
  port       = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
